### ISSUE TITLE
totpage

### ISSUE THREAD

**Issue by xR2** [alexishuf/ufsc-thesis-rn46-2019#5]
Eu estava tendo um erro por causa do lastpage, pois no meu pacote pessoal estava usando o totpage.

> Package totpages Error: Can't use both, lastpage and totpages

Pra resolver mudei a linha 327:

` \RequirePackage{totpages}`

Pelo que eu testei os comandos `thepage` tudo mais continuam todos compatíveis pois o [totpages](https://ctan.org/pkg/totpages?lang=en) já engloba o lastpage.

**Comment by alexishuf** [comment]
Obrigado por avisar, isso é um bug.

Investiguei e o lastpage não tem nenhum uso nesse template. Esse `\RequirePackage{}` está ali desde o primeiro commit e imagino que ele tenha vindo como parte de um código antigo de geração de ficha catalográfica, que deve ser gerada no site da BU e não em latex puro.

Como a política dessa classe é importar o minínimo de pacotes para evitar conflitos como esse que você teve, a melhor solução é remover o `\RequirePackage{lastpage}` completamente. 

Já fiz isso no commit 7dad814, no branch master. Basta fazer um pull ou trocar o `.cls` e você vai conseguir usar o `totpages` como tentou inicialmente.

Se o tudo der certo e nada mais quebrar, deixo as honras de fechar o issue com você.
