### ISSUE TITLE
Espaçamento nas listas

### ISSUE THREAD

**Issue by xR2** [alexishuf/ufsc-thesis-rn46-2019#8]
Me parece que há um espaço, quase uma linha extra, na lista de figuras, e o meu sumário esta ficando desalinhado. Pelo que entendi esse é o comportamento padrão do `memoir`, quando as figuras estão em diferentes capítulos. Não achei nada sobre isso na ABNT nem nas normas da UFSC.

![RUxAqAy](https://user-images.githubusercontent.com/17341234/151846036-724a10c0-de37-470d-90bd-5c74b89042ef.png)

A lista de figuras consegui "arrumar" com uma gambiarra, não sei exatamente como/onde isso seria implementado na classe, usando `\renewcommand*{\addvspace}[1]{}` . Talvez o melhor seja deixar isso como uma opção, e cada um escolhe como quer.

```
{
  \begingroup
    \renewcommand*{\addvspace}[1]{}
     \listoftables*
    %\listofalgorithms*
     \listoffigures*
    \thispagestyle{empty}
    \tableofcontents*
  \endgroup
}
```

O sumário:
![RUxAqAy](https://user-images.githubusercontent.com/17341234/151845146-350f5079-304c-4f6e-a7f3-c3d34c8b9185.png)

**Comment by alexishuf** [comment]
**Atualizei a classe** (confirme 0.9.1 no topo do .cls) para que o espaço na lista de figuras e tabela não exista por padrão.

Provavelmente a ninguém na BU decidiu remover o espaço e talvez a bibliotecária não se importe se perceber, mas a diferença pode ser justificativa de uma rejeição. Caso alguém precise trazer o espaço de volta, a opção da classe é `chapterspace`. 

Agora sobre esse teu sumário... Não faço idéia de qual poderia ser o problema. Não é a opção english nem capítulo sem seção. Veja como fica o manual da classe:

![sumario](https://user-images.githubusercontent.com/11590809/151854871-79b758b4-081e-47a9-82d7-7377d9371d33.png)

Alterar `\addvspace` pode ter efeitos colaterais mais graves, tente remover a gambiarra e atualizar a classe. Se isso não resolver, coloque o seu projeto no overleaf ou github e coloque o link aqui.

**Comment by xR2** [comment]
Não encontrei exatamente o que causa esse problema, talvez seja o cabeçalho customizado na abertura dos capítulos.
Mas consegui "resolver" com isso:

```
\addtocontents{toc}{\setlength  {\cftchapterindent }{0em} \setlength  {\cftchapternumwidth }{\cftlastnumwidth }}
```

Deveria ser zero mesmo, usei como referencia [essa pergunta/resposta](https://tex.stackexchange.com/a/50472/75648).

**Comment by alexishuf** [comment]
Se por **cabeçalho** você quer a numeração das páginas, você pode reverter o comportamento padrão do abntex com a opção `nocleanheader`. Mas o pagestyle configurado passa bem longe desses lengths problemáticos... Aqui eu testei e não causou o bug.

Investiguei algums lengths que podem estar envolvidos, mas em `/usr/share/texmf-dist/tex/latex` encontrei apenas arquivos .cls os alterando (que são inocentes pois estão fora do caminho ufsc-thesis -> abntex2 -> memoir)

Como alterar esses 2 lengths resolveu teu problema, alguém deve ter alterado um desses 3 lengths:

- `cftsubsubsectionnumwidth`
- `cftchapternumwidth`
- `cftchapterindent`

É possível que alguem tenha alterado `\cft*font` e deixado algo além de macros de seleção de fontes, como uma quebra de linha acidental. Procure por alterações dessas em `\cftchapterfont`

Um `find . -type f -exec grep -Hn cftchapterfont '{}' \;` no teu projeto ou no teu /usr/share/texmf-dist deve mostrar usos e alterações.

Outra forma de encontrar o culpado é tirar os `\setlengths` que você fez de dentro do `\addtocontents{toc}`, e ir movendo eles para cima no teu preambulo (antes do \tableofcontents). Em algum momento eles vão deixar de arrumar e o código entre a posição atual e a posição antiga dos `\setlength` é o culpado.
